pixel_strip:
  ros__parameters:
    # led strip configuration:
    led_count: 148 # Number of led pixels.
    led_pin: 18          # GPIO pin connected to the pixels (18 uses PWM!).
    # led_pin: 10        # GPIO pin connected to the pixels (10 uses SPI /dev/spidev0.0).
    led_freq_hz: 800000  # led signal frequency in hertz (usually 800khz)
    led_dma: 10          # DMA channel to use for generating signal (try 10)
    led_brightness: 255  # Set to 0 for darkest and 255 for brightest
    led_invert: False    # True to invert the signal (when using NPN transistor level shift)
    led_channel: 0       # set to '1' for GPIOs 13, 19, 41, 45 or 53   
